FROM python:3.11-slim

WORKDIR /app

ENV PYTHONPATH=/app

COPY req.txt .

RUN pip install --no-cache-dir -r req.txt && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    python3-tk \
    && rm -rf /var/lib/apt/lists/*

COPY . .

CMD ["python", "main.py"]
