name: DnD Dice Tests

on:
  push:
    branches: [ "DnD" ]

jobs:
  setup-python:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"
      - name: Install pytest
        run: pip install pytest

  run-app-on-windows:
    runs-on: windows-latest
    needs: setup-python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run unit tests
        shell: pwsh
        run: python -m pytest tests --maxfail=1 --disable-warnings -q | Out-File test_log.txt -Encoding utf8

      - name: Upload test logs
        uses: actions/upload-artifact@v4
        with:
          name: pytest-logs
          path: test_log.txt