name: DnDHelper CI

on:
  push:
    branches: [ "DnD" ]

jobs:
  run-app-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Instalacja zależności
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Uruchom aplikację
        run: python main.py
        
  run-app-on-windows:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Instalacja zależności
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Uruchom aplikację
        run: python main.py