name: DnD Helper CI/CD

on:
  pull_request:
    branches: [ "DnD" ]   #workflow works only for PRs to DnD branch

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Install deps
        run: |
          if (Test-Path req.txt) {
            python -m pip install -r req.txt
          } else {
            Write-Host "No req.txt found, skipping dependency installation."
          }

      - name: Run tests
        run: pytest Tests/ --maxfail=1 --disable-warnings -q | tee test_log.txt

  build:
    needs: test             # build job runs only if test job is successful
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Install deps
        run: python -m pip install -r req.txt

      - name: Build exe with PyInstaller
        run: pyinstaller --onefile main.py --distpath dist --add-data "Data;Data"

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dnd-helper-exe
          path: dist/main.exe

          