name: DnDHelper CI

on:
  push:
    branches: [ "DnD" ]

jobs:      
  run-app-on-windows:
    runs-on: windows-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Check dependencies
        shell: pwsh
        run: |
          if (Test-Path "requirements.txt") {
              pip install -r requirements.txt
          } else {
              Write-Host "No requirements.txt found, skipping dependency installation."   
          }
      - name: App Start
        run: python main.py --test